# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=255, verbose_name='제목'),
        ),
    ]
